### ISSUE TITLE
Linux build instructions

### ISSUE THREAD

**Issue by potatoeggy** [SkyTemple/skytemple#5]
A brief glance at the code seems like it can be run on Linux, and the YouTube video has what is definitely a non-Windows DE in it. Could you provide build instructions for the wee minority of us using Linux?

**Comment by Parakoopa** [comment]
Hi, depending on what you want to do, you basically only need to do step 4 and 5 of the Windows instructions, because you most likely already have both Python and GTK installed and the binary dependencies all have wheels for Linux directly on the Python package index, which are automatically downloaded.

**Comment by potatoeggy** [comment]
Great, thanks!
